export const HINT = {
    EXTRACT_POSITION: 1,
    RANGE_OF_ROOMS: 2,
    RELATIVE_DIRECTION: 3,
    RELATIVE_DIRECTION_DIAGONAL: 4,
    DISTANCE: 5,
    ROW_COLUMN_ALIGNMENT_FOX: 6,
    ROW_COLUMN_ALIGNMENT_HIDERS: 7,
    ROW_COLUMN_DIFF: 8,
    HIDING_AT_CONNER: 9,
    NOTTHNG: 10,
};
